"""added mastery column

Revision ID: cd8ec3b825ee
Revises: 72de621fb404
Create Date: 2022-10-03 13:22:26.312096

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

# revision identifiers, used by Alembic.
revision = 'cd8ec3b825ee'
down_revision = '72de621fb404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if environment == "production":
        op.add_column('cards', sa.Column('mastery', sa.Integer(), nullable=True), schema=SCHEMA)
    else:
        op.add_column('cards', sa.Column('mastery', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'mastery')
    # ### end Alembic commands ###
